spring.datasource.url=jdbc:sqlserver://localhost\\MSSQLSERVER01;databaseName=contact_management;encrypt=false;integratedSecurity=true

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm=DEBUG